### ISSUE TITLE
Dataset Joining problem

### ISSUE THREAD

**Issue by jwu13** [jwu13/sds192-mp2#3]
Hi! I have a question on joining issue, can anyone tell me the difference between inner_join, left_join, and right_join?

**Comment by Irene-Xu-mengye** [comment]
I think inner_join joins two tables but leave out rows if either table doesn't have a value for that row. left_join leaves all the rows present in the first table and assign NA to the second if the value is missing. right_join leaves the rows in the second table and assign NA to the first table if the value is missing.

**Comment by SarahWu99** [comment]
The way I perceive this is that the Inner join has the least NAs cuz it drops NAs from both data frames you're joining. Left join uses the first data frame as the basis and leave NAs for any data that is missing from the second joined data frame. Right join is the opposite of left join. Full join keeps all of the NAs from both data frames.
